### ISSUE TITLE
This might be creating a new dataLocation when you modify an existing one 

### ISSUE THREAD

**Issue by Tich1212** [HydrologicEngineeringCenter/BasicPlugin#1]
https://github.com/HydrologicEngineeringCenter/BasicPlugin/blob/145b86e85ee6e240b0f27670e80d1a99f6ea6e23/src/basicplugin/BasicAlternative.java#L125

In the CAVI equivalent of this plugin my experience was that this line was adding a new dataLocation when the location was edited in the model linking editor. I used a set instead of an add where is the index of the existing location.

```
                    _dataLocations.set(i, dl);
//                    _dataLocations.add(dl);
```

**Comment by HenryGeorgist** [comment]
that might be a difference between WAT and CAVI - i would need to test that to see. it would depend on the backing list i think.

**Comment by HenryGeorgist** [comment]
the line you linked is inside of an if condition to determine if the list does not already contain that data location
https://github.com/HydrologicEngineeringCenter/BasicPlugin/blob/145b86e85ee6e240b0f27670e80d1a99f6ea6e23/src/basicplugin/BasicAlternative.java#L118

so adding is the proper action - if the list already contains it, we set modified as true.

T
